-- Run connected AS WMS_LOG (owner of LOGGER / LOGGER_LOGS), not WMS_LIQUIBASE:
-- SELECT ANY TABLE / EXECUTE ANY PROCEDURE on WMS_ADMIN_ROLE let WMS_LIQUIBASE
-- use these objects, but object-privilege GRANTs must come from the owner.
--
-- Depends on WMS_LOG.LOGGER (package) and WMS_LOG.LOGGER_LOGS (table) already
-- existing -- not yet created as of this commit. Run this after that DDL lands.

GRANT EXECUTE ON LOGGER TO WMS_APP;
GRANT EXECUTE ON LOGGER TO WMS_APP_PROC;
GRANT EXECUTE ON LOGGER TO WMS_APEX;
GRANT EXECUTE ON LOGGER TO WMS_LOG_PROC;

GRANT SELECT ON LOGGER_LOGS TO WMS_APP;
GRANT SELECT ON LOGGER_LOGS TO WMS_APP_PROC;
GRANT SELECT ON LOGGER_LOGS TO WMS_APEX;
GRANT SELECT ON LOGGER_LOGS TO WMS_LOG_PROC;
