GRANT EXECUTE ON LOGGER TO WMS_APP;
GRANT EXECUTE ON LOGGER TO WMS_APP_PROC;
GRANT EXECUTE ON LOGGER TO WMS_APEX;
GRANT EXECUTE ON LOGGER TO WMS_LOG_PROC;

GRANT SELECT ON LOGGER_LOGS TO WMS_APP;
GRANT SELECT ON LOGGER_LOGS TO WMS_APP_PROC;
GRANT SELECT ON LOGGER_LOGS TO WMS_APEX;
GRANT SELECT ON LOGGER_LOGS TO WMS_LOG_PROC;
