DECLARE
   l_exists NUMBER;
BEGIN
   SELECT CASE WHEN EXISTS (SELECT 1 FROM dba_users WHERE username = 'WMS_LIQUIBASE') THEN 1 ELSE 0 END
   INTO l_exists FROM dual;

   IF l_exists = 1 THEN
      EXECUTE IMMEDIATE 'DROP USER WMS_LIQUIBASE CASCADE';
   END IF;

   SELECT CASE WHEN EXISTS (SELECT 1 FROM dba_roles WHERE role = 'WMS_ADMIN_ROLE') THEN 1 ELSE 0 END
   INTO l_exists FROM dual;

   IF l_exists = 1 THEN
      EXECUTE IMMEDIATE 'DROP ROLE WMS_ADMIN_ROLE';
   END IF;
END;
/
