SET VERIFY OFF
DEFINE password = &1

CREATE ROLE WMS_ADMIN_ROLE;

GRANT CREATE SESSION TO WMS_ADMIN_ROLE WITH ADMIN OPTION;
GRANT CREATE USER    TO WMS_ADMIN_ROLE;
GRANT ALTER USER     TO WMS_ADMIN_ROLE;
GRANT DROP USER      TO WMS_ADMIN_ROLE;
GRANT CREATE ROLE    TO WMS_ADMIN_ROLE;

GRANT SELECT_CATALOG_ROLE   TO WMS_ADMIN_ROLE;

GRANT CREATE ANY TABLE      TO WMS_ADMIN_ROLE;
GRANT ALTER ANY TABLE       TO WMS_ADMIN_ROLE;
GRANT SELECT ANY TABLE      TO WMS_ADMIN_ROLE;
GRANT INSERT ANY TABLE      TO WMS_ADMIN_ROLE;
GRANT UPDATE ANY TABLE      TO WMS_ADMIN_ROLE;
GRANT DELETE ANY TABLE      TO WMS_ADMIN_ROLE;
GRANT DROP ANY TABLE        TO WMS_ADMIN_ROLE;
GRANT COMMENT ANY TABLE     TO WMS_ADMIN_ROLE; 

GRANT CREATE ANY VIEW       TO WMS_ADMIN_ROLE;
GRANT DROP ANY VIEW         TO WMS_ADMIN_ROLE;

GRANT CREATE ANY SEQUENCE   TO WMS_ADMIN_ROLE;
GRANT DROP ANY SEQUENCE     TO WMS_ADMIN_ROLE;

GRANT CREATE ANY PROCEDURE  TO WMS_ADMIN_ROLE;
GRANT DROP ANY PROCEDURE    TO WMS_ADMIN_ROLE;

GRANT CREATE ANY TRIGGER    TO WMS_ADMIN_ROLE;
GRANT DROP ANY TRIGGER      TO WMS_ADMIN_ROLE;
GRANT ALTER ANY TRIGGER     TO WMS_ADMIN_ROLE;

GRANT CREATE ANY TYPE       TO WMS_ADMIN_ROLE;
GRANT DROP ANY TYPE         TO WMS_ADMIN_ROLE;

GRANT CREATE ANY JOB        TO WMS_ADMIN_ROLE;

GRANT CREATE ANY CONTEXT    TO WMS_ADMIN_ROLE;
GRANT DROP ANY CONTEXT      TO WMS_ADMIN_ROLE;

GRANT CREATE ANY INDEX      TO WMS_ADMIN_ROLE;
GRANT DROP ANY INDEX        TO WMS_ADMIN_ROLE;


GRANT EXECUTE ANY PROCEDURE TO WMS_ADMIN_ROLE;

-- WMS-LIQUIBASE-USER

CREATE USER WMS_LIQUIBASE IDENTIFIED BY "&password"
   DEFAULT TABLESPACE users
   TEMPORARY TABLESPACE temp
   QUOTA 0 ON users;

GRANT WMS_ADMIN_ROLE TO WMS_LIQUIBASE WITH ADMIN OPTION;
ALTER USER WMS_LIQUIBASE DEFAULT ROLE WMS_ADMIN_ROLE;


GRANT EXECUTE ON DBMS_AQADM TO WMS_LIQUIBASE WITH GRANT OPTION;
GRANT EXECUTE ON DBMS_AQ    TO WMS_LIQUIBASE WITH GRANT OPTION;

UNDEFINE password
