SET VERIFY OFF
DEFINE password = &1

CREATE ROLE WMS_ADMIN_ROLE;

GRANT CREATE SESSION TO WMS_ADMIN_ROLE;
GRANT CREATE USER    TO WMS_ADMIN_ROLE;
GRANT ALTER USER     TO WMS_ADMIN_ROLE;
GRANT DROP USER      TO WMS_ADMIN_ROLE;
GRANT CREATE ROLE    TO WMS_ADMIN_ROLE;

--WMS-LIQUIBASE-USER

CREATE USER WMS_LIQUIBASE IDENTIFIED BY "&password"
   DEFAULT TABLESPACE users
   TEMPORARY TABLESPACE temp
   QUOTA 0 ON users;

GRANT WMS_ADMIN_ROLE TO WMS_LIQUIBASE;
ALTER USER WMS_LIQUIBASE DEFAULT ROLE WMS_ADMIN_ROLE;

UNDEFINE password
