SET VERIFY OFF
DEFINE password = &1

CREATE USER WMS_APP_PROC IDENTIFIED BY "&password"
   DEFAULT TABLESPACE users
   TEMPORARY TABLESPACE temp
   QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO WMS_APP_PROC;
GRANT EXECUTE ON DBMS_AQ TO WMS_APP_PROC;

UNDEFINE password
