GRANT EXECUTE ON LOGGER TO WMS_APP;
GRANT EXECUTE ON LOGGER TO WMS_APEX;
GRANT EXECUTE ON LOGGER TO WMS_APP_PROC;
GRANT EXECUTE ON LOGGER TO WMS_LOG_PROC;

GRANT SELECT ON LOGGER_LOGS TO WMS_LIQUIBASE;
GRANT SELECT ON LOGGER_LOGS TO WMS_APP;
GRANT SELECT ON LOGGER_LOGS TO WMS_APEX;
GRANT SELECT ON LOGGER_LOGS TO WMS_APP_PROC;
GRANT SELECT ON LOGGER_LOGS TO WMS_LOG_PROC;

GRANT SELECT ON LOGGER_LOGS_APEX_ITEMS TO WMS_APP;
GRANT SELECT ON LOGGER_LOGS_APEX_ITEMS TO WMS_APEX;
GRANT SELECT ON LOGGER_LOGS_APEX_ITEMS TO WMS_APP_PROC;
GRANT SELECT ON LOGGER_LOGS_APEX_ITEMS TO WMS_LOG_PROC;

GRANT SELECT ON LOGGER_PREFS TO WMS_APP;
GRANT SELECT ON LOGGER_PREFS TO WMS_APEX;
GRANT SELECT ON LOGGER_PREFS TO WMS_APP_PROC;
GRANT SELECT ON LOGGER_PREFS TO WMS_LOG_PROC;


GRANT SELECT ON LOGGER_PREFS_BY_CLIENT_ID TO WMS_APP;
GRANT SELECT ON LOGGER_PREFS_BY_CLIENT_ID TO WMS_APEX;
GRANT SELECT ON LOGGER_PREFS_BY_CLIENT_ID TO WMS_APP_PROC;
GRANT SELECT ON LOGGER_PREFS_BY_CLIENT_ID TO WMS_LOG_PROC;

GRANT SELECT ON LOGGER_LOGS_5_MIN TO WMS_APP;
GRANT SELECT ON LOGGER_LOGS_5_MIN TO WMS_APEX;
GRANT SELECT ON LOGGER_LOGS_5_MIN TO WMS_APP_PROC;
GRANT SELECT ON LOGGER_LOGS_5_MIN TO WMS_LOG_PROC;

GRANT SELECT ON LOGGER_LOGS_60_MIN TO WMS_APP;
GRANT SELECT ON LOGGER_LOGS_60_MIN TO WMS_APEX;
GRANT SELECT ON LOGGER_LOGS_60_MIN TO WMS_APP_PROC;
GRANT SELECT ON LOGGER_LOGS_60_MIN TO WMS_LOG_PROC;

GRANT SELECT ON LOGGER_LOGS_TERSE TO WMS_APP;
GRANT SELECT ON LOGGER_LOGS_TERSE TO WMS_APEX;
GRANT SELECT ON LOGGER_LOGS_TERSE TO WMS_APP_PROC;
GRANT SELECT ON LOGGER_LOGS_TERSE TO WMS_LOG_PROC;
