SET VERIFY OFF
DEFINE password = &1

CREATE USER WMS_APP IDENTIFIED BY "&password"
   DEFAULT TABLESPACE users
   TEMPORARY TABLESPACE temp
   QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO WMS_APP;

UNDEFINE password
