SET VERIFY OFF
DEFINE password = &1

CREATE USER WMS_LOG_PROC IDENTIFIED BY "&password"
   DEFAULT TABLESPACE users
   TEMPORARY TABLESPACE temp
   QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO WMS_LOG_PROC;
GRANT EXECUTE ON DBMS_AQ TO WMS_LOG_PROC;

UNDEFINE password
